/// <reference types="node" />
import { readFileSync } from 'node:fs'
import { join } from 'node:path'
import { describe, expect, it } from 'vitest'

// Read from disk: Vitest does not process CSS, so `import css from './index.css?raw'` yields an empty string.
const css = readFileSync(join(import.meta.dirname, 'index.css'), 'utf8')

// Every app source file (tests and test helpers excluded) as text, keyed by path relative to src/.
const sources = import.meta.glob<string>(['./**/*.{ts,tsx}', '!./**/*.test.{ts,tsx}', '!./test/**'], {
  query: '?raw',
  import: 'default',
  eager: true,
})

/** Text of the first `<selector> { … }` block in index.css (up to its first closing brace). */
function block(selector: string): string {
  const start = css.indexOf(`${selector} {`)
  expect(start, `"${selector} {" in index.css`).toBeGreaterThanOrEqual(0)
  return css.slice(start, css.indexOf('}', start))
}

const THEME_COLORS = [
  'background',
  'foreground',
  'card',
  'popover',
  'primary',
  'primary-foreground',
  'secondary',
  'muted',
  'muted-foreground',
  'accent',
  'destructive',
  'border',
  'input',
  'ring',
  'sidebar',
  'sidebar-foreground',
  'sidebar-primary',
  'sidebar-accent',
]

describe('theme', () => {
  it.each(THEME_COLORS)('defines --%s as a CSS variable for light and dark mode', (name) => {
    expect(block(':root')).toContain(`--${name}:`)
    expect(block('.dark')).toContain(`--${name}:`)
  })

  it.each(THEME_COLORS)('maps the Tailwind color "%s" to its CSS variable', (name) => {
    expect(block('@theme inline')).toContain(`--color-${name}: var(--${name});`)
  })

  it('loads a font with Arabic glyphs after the Latin font (Geist has no Arabic)', () => {
    expect(css).toContain('@import "@fontsource-variable/noto-sans-arabic";')
    expect(block('@theme inline')).toContain(`--font-sans: 'Geist Variable', 'Noto Sans Arabic Variable', sans-serif;`)
  })

  it('scans the app sources', () => {
    expect(Object.keys(sources)).toContain('./App.tsx')
    expect(Object.keys(sources)).toContain('./components/ui/button.tsx')
  })

  it('uses no hard-coded hex colors in source files', () => {
    const offenders = Object.entries(sources)
      // The generated shadcn chart only names Recharts' default "#ccc" / "#fff" attributes in selectors to restyle them
      // with theme variables; it paints nothing with a hex color.
      .filter(([path]) => path !== './components/ui/chart.tsx')
      .filter(([, text]) => /#[0-9a-fA-F]{3,8}\b/.test(text))
      .map(([path]) => path)
    expect(offenders).toEqual([])
  })

  it('uses logical (RTL-safe) direction classes in app components', () => {
    const physical =
      /(?<![\w-])-?(?:ml|mr|pl|pr|left|right)-[\w[]|(?<![\w-])(?:text|float)-(?:left|right)\b|(?<![\w-])(?:border|rounded)-[lr](?:-|\b)/
    const offenders = Object.entries(sources)
      // components/ui is generated by the shadcn CLI (initialised with --rtl) and is not edited by hand.
      .filter(([path]) => !path.startsWith('./components/ui/'))
      .filter(([, text]) => physical.test(text))
      .map(([path]) => path)
    expect(offenders).toEqual([])
  })
})
